In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot  as plt
import seaborn as sns

In [8]:
advertisement = pd.read_csv("tvmarketing.csv")
advertisement

        TV  Sales
0    230.1   22.1
1     44.5   10.4
2     17.2    9.3
3    151.5   18.5
4    180.8   12.9
..     ...    ...
195   38.2    7.6
196   94.2    9.7
197  177.0   12.8
198  283.6   25.5
199  232.1   13.4

[200 rows x 2 columns]

In [11]:
advertisement.describe()

               TV       Sales
count  200.000000  200.000000
mean   147.042500   14.022500
std     85.854236    5.217457
min      0.700000    1.600000
25%     74.375000   10.375000
50%    149.750000   12.900000
75%    218.825000   17.400000
max    296.400000   27.000000

# visulaization data using seaborn

In [ ]:
sns.pairplot(advertisement , x_vars=["TV"], y_vars=["Sales"],size= 7,aspect=0.7 , kind="scatter")